wrapper.jarFile = ".gradle/wrapper/gradle-wrapper.jar"

layout.buildDirectory.set(layout.projectDirectory.dir('.build'))
subprojects {
    apply plugin: 'java'

    layout.buildDirectory.set(layout.projectDirectory.dir('.build'))

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(22)
            vendor = JvmVendorSpec.AMAZON
        }
    }

    compileJava {
        options.release = 22
    }

    compileTestJava {
        options.release = 22
    }
}

ext {
    strata_foundation_version = "1.0-SNAPSHOT"

    spring_version = "6.2.2"
    springboot_version = "3.4.1"
    //spring_guice_version = "3.0.0"
    //spring_kafka_version = "3.3.1"
    //springdoc_version = "2.8.4"

    //guice_version = "7.0.0"
    jackson_version = "2.21.1"
    httpclient_version = "5.6"
    //avro_version = "1.12.1"
    //kafka_version = "3.8.0"
    //chronicle_queue_version = "5.26ea9"
    //hibernate_version = "6.4.4.Final"
    log4j_version = "2.25.3"
    jasypt_version = "1.9.3"

    //confluent_kafka_version = "3.4.0"
    //confluent_avro_version = "8.2.0"

    //jakarta_inject_version = "2.0.1"
    jakarta_ws_rs_version = "4.0.0"
    jakarta_websocket_version = "2.3.0-M2"

    jboss_resteasy_version = "7.0.0.Final"
    eclipse_websocket_version = "11.0.26"

    junit_jupiter_version = "5.13.3"
    junit_platform_version = "1.13.3"

    major = "1"
    minor = "0"
    patch = "SNAPSHOT"
    separator1 = "."
    separator2 = "-"
}

group 'strata.client'
version "$major$separator1$minor$separator2$patch"