name: Development-Pipeline
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROPERTIES_ENCRYPTION_KEY: ${{secrets.PROPERTIES_ENCRYPTION_KEY}}
  REPOSITORY_USER: ${{vars.REPOSITORY_USER}}
  REPOSITORY_PASSWORD: ${{secrets.REPOSITORY_PASSWORD}}
  DOCKER_USER: ${{vars.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  typescript-commit-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.5.1'
          registry-url: 'https://registry.npmjs.org/'
          always-auth: 'true'

      - name: Cache Node Modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            **/node_modules
            .yarn/cache
            .pnp.*
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dev dependencies with Yarn
        run: yarn install --dev --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

      - name: Build Typescript with Yarn
        run: yarn run test

  java-commit-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'corretto'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
            build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Chmod GradleW
        run: chmod a+x gradlew

      - name: Build Java with Gradle
        run: ./gradlew build

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/build/libs/*.jar
          retention-days: 1
          include-hidden-files: 'true'

      - name: Publish Test Report (Commit Stage)
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
            report_paths: '**/build/test-results/test/TEST-*.xml'

#  java-integration-stage:
#    runs-on: ubuntu-latest
#    needs: java-commit-stage
#    steps:
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{vars.REPOSITORY_USER}}
#          password: ${{secrets.REPOSITORY_PASSWORD}}
#
#      - name: Pull Strata.Client.TestSuite Image
#        run: docker pull ghcr.io/johnliebenau/strata.client/strata-client-testsuite:1.0-SNAPSHOT
#
#      - name: Run Strata.Client.TestSuite Integration Tests
#        run: |
#          docker run ghcr.io/johnliebenau/strata.client/strata-client-testsuite:1.0-SNAPSHOT \
#            --package=strata.foundation --tags=IntegrationStage
#
#  java-acceptance-stage:
#    runs-on: ubuntu-latest
#    needs: java-integration-stage
#    steps:
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{vars.REPOSITORY_USER}}
#          password: ${{secrets.REPOSITORY_PASSWORD}}
#
#      - name: Pull Strata.Client.TestSuite Image
#        run: docker pull ghcr.io/johnliebenau/strata.client/strata-client-testsuite:1.0-SNAPSHOT
#
#      - name: Run Strata.Client.TestSuite Acceptance Tests
#        run: |
#          docker run ghcr.io/johnliebenau/strata.client/strata-client-testsuite:1.0-SNAPSHOT \
#            --package=strata.foundation --tags=AcceptanceStage

  java-deploy-stage:
    runs-on: ubuntu-latest
    needs: java-commit-stage
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Chmod GradleW
        run: chmod a+x gradlew

      - name: Chmod GradleW
        run: chmod a+x gradlew

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Publish Build Artifacts
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository -x test -x build -x jar -x compileJava -x processResources -x classes -x testJar -x testFixturesJar -x testClasses -x testFixturesClasses


